export const BENIN_COMMUNES_BY_DEPARTEMENT = {
  Alibori: [
    "Banikoara",
    "Gogounou",
    "Kandi",
    "Karimama",
    "Malanville",
    "Ségbana",
  ],
  Atacora: [
    "Boukoumbé",
    "Cobly",
    "Kérou",
    "Kouandé",
    "Matéri",
    "Natitingou",
    "Pehunco",
    "Tanguiéta",
    "Toucountouna",
  ],
  Atlantique: [
    "Abomey-Calavi",
    "Allada",
    "Kpomassè",
    "Ouidah",
    "Sô-Ava",
    "Toffo",
    "Tori-Bossito",
    "Zè",
  ],
  Borgou: [
    "Bembèrèkè",
    "Kalalé",
    "N'Dali",
    "Nikki",
    "Parakou",
    "Pèrèrè",
    "Sinendé",
    "Tchaourou",
  ],
  Collines: [
    "Bantè",
    "Dassa-Zoumè",
    "Glazoué",
    "Ouèssè",
    "Savalou",
    "Savè",
  ],
  Couffo: [
    "Aplahoué",
    "Djakotomey",
    "Dogbo",
    "Klouékanmè",
    "Lalo",
    "Toviklin",
  ],
  Donga: [
    "Bassila",
    "Copargo",
    "Djougou",
    "Ouaké",
  ],
  Littoral: [
    "Cotonou",
  ],
  Mono: [
    "Athiémé",
    "Bopa",
    "Comè",
    "Grand-Popo",
    "Houéyogbé",
    "Lokossa",
  ],
  Ouémé: [
    "Adjarra",
    "Adjohoun",
    "Aguégués",
    "Akpro-Missérété",
    "Avrankou",
    "Bonou",
    "Dangbo",
    "Porto-Novo",
    "Sèmè-Podji",
  ],
  Plateau: [
    "Adja-Ouèrè",
    "Ifangni",
    "Kétou",
    "Pobè",
    "Sakété",
  ],
  Zou: [
    "Abomey",
    "Agbangnizoun",
    "Bohicon",
    "Covè",
    "Djidja",
    "Ouinhi",
    "Za-Kpota",
    "Zagnanado",
    "Zogbodomey",
  ],
};

export const DEPARTEMENTS = Object.keys(BENIN_COMMUNES_BY_DEPARTEMENT).sort();

export const ALL_COMMUNES = Object.values(BENIN_COMMUNES_BY_DEPARTEMENT)
  .flat()
  .sort((a, b) => a.localeCompare(b, "fr"));
